# Generated by Django 5.2.12 on 2026-03-25 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_add_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('gcs_object_key', models.CharField(help_text='Object key in bucket or relative path under MEDIA_ROOT for local dev.', max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.coursematerial')),
            ],
            options={
                'ordering': ['material', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='AiInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('response_tokens', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='courses.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='ai_aiintera_operati_efc67b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course', 'processing_status'], name='ai_coursema_course__63e19d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialchunk',
            index=models.Index(fields=['material', 'chunk_index'], name='ai_material_materia_9cfbdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialchunk',
            unique_together={('material', 'chunk_index')},
        ),
    ]
