# Generated by Django 5.2.13 on 2026-04-15 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_topic'),
        ('quizzes', '0002_add_question_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='Ordinal of this response within the quiz attempt (1-based).'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionIRTParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_b', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irt_parameter', to='quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_ability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicBKTParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_l0', models.FloatField(default=0.35)),
                ('p_t', models.FloatField(default=0.1)),
                ('p_g', models.FloatField(default=0.25)),
                ('p_s', models.FloatField(default=0.1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_parameters', to='courses.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_knowledge', models.FloatField(default=0.35)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='courses.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='uniq_quizzes_student_topic_mastery')],
            },
        ),
    ]
