# Generated by Django 5.2.12 on 2026-03-25 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_topic'),
        ('quizzes', '0002_add_question_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='review_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'difficulty', 'is_active', 'review_status'], name='quizzes_que_chapter_fafe00_idx'),
        ),
    ]
