# Generated by Django 5.2.12 on 2026-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_oauth_id_alter_user_oauth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email allowed to create new accounts.', max_length=254, unique=True)),
                ('student_allowed', models.BooleanField(default=True, help_text='Whether this email can sign up as student.')),
                ('instructor_allowed', models.BooleanField(default=False, help_text='Whether this email can sign up as instructor/admin.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allowlist entry is active.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional operational note about this entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signup Allowlist Entry',
                'verbose_name_plural': 'Signup Allowlist Entries',
                'ordering': ['email'],
            },
        ),
    ]
