# Generated by Django 5.2.12 on 2026-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_signupallowlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupallowlist',
            name='instructor_allowed',
            field=models.BooleanField(default=False, help_text='Whether this email can sign up as instructor.'),
        ),
        migrations.AlterField(
            model_name='signupallowlist',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this allowlist entry is active when allowlist checks are enabled.'),
        ),
    ]
